IF
	True()
THEN
	RESPONSE #100
		CutSceneId("agdeano")
		ReallyForceSpell("agdeimos",DO_NOTHING)
		Wait(1)
		CreateVisualEffectObject("SPTENSTT","agdeimos")
		ActionOverride("agdeimos",Polymorph(KOBOLD_XVART))
		Wait(2)
		ActionOverride("agdeimos",EscapeArea())
		DisplayStringHead("agdeano",18673) // And this should redeem you for all you have done?  I say it is a fitting punishment!
		Wait(2)
		EndCutSceneMode()
		SetGlobal("bosstime","MYAREA",1)
		EscapeArea()
END

